[window]
opacity = 0.5
padding.x = 30
padding.y = 30
decorations = "None"
decorations_theme_variant = "None"

[font]
normal = { family = "Adwaita Mono"}
bold = { family = "Adwaita Mono", style = "Bold"}
italic = { family = "Adwaita Mono", style = "Italic"}
bold_italic = { family = "Adwaita Mono", style = "Bold Italic"}
size = 14

[cursor]
style.shape = "Underline"
style.blinking = "Off"
blink_interval = 500

[colors.primary]
background = "#303030"

[colors.selection]
text = "#202020"
background = "#4baac9"

[colors.normal]
blue = "#1ce67a"
